2023-09-02 01:22:05,723:DEBUG:certbot._internal.main:certbot version: 2.6.0
2023-09-02 01:22:05,723:DEBUG:certbot._internal.main:Location of certbot entry point: /usr/local/bin/certbot
2023-09-02 01:22:05,723:DEBUG:certbot._internal.main:Arguments: ['--webroot', '--webroot-path=/var/www/certbot', '--email', 'arifin@lenna.ai', '--agree-tos', '--no-eff-email', '-d', 'backend.arifinportfolio.my.id']
2023-09-02 01:22:05,724:DEBUG:certbot._internal.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2023-09-02 01:22:05,805:DEBUG:certbot._internal.log:Root logging level set at 30
2023-09-02 01:22:05,806:DEBUG:certbot._internal.plugins.selection:Requested authenticator webroot and installer None
2023-09-02 01:22:05,810:DEBUG:certbot._internal.plugins.selection:Single candidate plugin: * webroot
Description: Saves the necessary validation files to a .well-known/acme-challenge/ directory within the nominated webroot path. A seperate HTTP server must be running and serving files from the webroot path. HTTP challenge only (wildcards not supported).
Interfaces: Authenticator, Plugin
Entry point: webroot = certbot._internal.plugins.webroot:Authenticator
Initialized: <certbot._internal.plugins.webroot.Authenticator object at 0x7fdbe95df280>
Prep: True
2023-09-02 01:22:05,811:DEBUG:certbot._internal.plugins.selection:Selected authenticator <certbot._internal.plugins.webroot.Authenticator object at 0x7fdbe95df280> and installer None
2023-09-02 01:22:05,811:INFO:certbot._internal.plugins.selection:Plugins selected: Authenticator webroot, Installer None
2023-09-02 01:22:06,133:DEBUG:certbot._internal.main:Picked account: <Account(RegistrationResource(body=Registration(key=None, contact=(), agreement=None, status=None, terms_of_service_agreed=None, only_return_existing=None, external_account_binding=None), uri='https://acme-v02.api.letsencrypt.org/acme/acct/1287359976', new_authzr_uri=None, terms_of_service=None), e621adeecf2172f31b158d59c11da4a7, Meta(creation_dt=datetime.datetime(2023, 9, 2, 0, 34, 47, tzinfo=<UTC>), creation_host='6837dab21189', register_to_eff=None))>
2023-09-02 01:22:06,134:DEBUG:acme.client:Sending GET request to https://acme-v02.api.letsencrypt.org/directory.
2023-09-02 01:22:06,137:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): acme-v02.api.letsencrypt.org:443
2023-09-02 01:22:06,792:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "GET /directory HTTP/1.1" 200 752
2023-09-02 01:22:06,793:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Sat, 02 Sep 2023 01:22:06 GMT
Content-Type: application/json
Content-Length: 752
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "keyChange": "https://acme-v02.api.letsencrypt.org/acme/key-change",
  "meta": {
    "caaIdentities": [
      "letsencrypt.org"
    ],
    "termsOfService": "https://letsencrypt.org/documents/LE-SA-v1.3-September-21-2022.pdf",
    "website": "https://letsencrypt.org"
  },
  "newAccount": "https://acme-v02.api.letsencrypt.org/acme/new-acct",
  "newNonce": "https://acme-v02.api.letsencrypt.org/acme/new-nonce",
  "newOrder": "https://acme-v02.api.letsencrypt.org/acme/new-order",
  "renewalInfo": "https://acme-v02.api.letsencrypt.org/draft-ietf-acme-ari-01/renewalInfo/",
  "revokeCert": "https://acme-v02.api.letsencrypt.org/acme/revoke-cert",
  "rli3sIcgYWo": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417"
}
2023-09-02 01:22:06,794:DEBUG:certbot._internal.display.obj:Notifying user: Requesting a certificate for backend.arifinportfolio.my.id
2023-09-02 01:22:06,835:DEBUG:acme.client:Requesting fresh nonce
2023-09-02 01:22:06,835:DEBUG:acme.client:Sending HEAD request to https://acme-v02.api.letsencrypt.org/acme/new-nonce.
2023-09-02 01:22:07,034:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "HEAD /acme/new-nonce HTTP/1.1" 200 0
2023-09-02 01:22:07,034:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Sat, 02 Sep 2023 01:22:06 GMT
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 2zuXfv7ZP1hdOXoCaQ8hQvrRXauw_kkCwhbbw_PRS25TkssqfEg
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800


2023-09-02 01:22:07,035:DEBUG:acme.client:Storing nonce: 2zuXfv7ZP1hdOXoCaQ8hQvrRXauw_kkCwhbbw_PRS25TkssqfEg
2023-09-02 01:22:07,035:DEBUG:acme.client:JWS payload:
b'{\n  "identifiers": [\n    {\n      "type": "dns",\n      "value": "backend.arifinportfolio.my.id"\n    }\n  ]\n}'
2023-09-02 01:22:07,075:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/new-order:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMTI4NzM1OTk3NiIsICJub25jZSI6ICIyenVYZnY3WlAxaGRPWG9DYVE4aFF2clJYYXV3X2trQ3doYmJ3X1BSUzI1VGtzc3FmRWciLCAidXJsIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL25ldy1vcmRlciJ9",
  "signature": "TFj_mDtsaOm0kOxz_NqK2HijGGx0NjnOKMN1Vwl6NRgxW_AyDpIl-v6Eh-t_JCYQMYsRr3tHr2ppjJxcU3lSjQd4BpY2wW2YQfG9qk6cmaIhiJYPQLPoTm8vfspHMSzqtjPcSYngV6cKSfi_8h5f1_Dl52ahV756u1tX4XFj5tpVqrjkkufl73Kp_re8MLWSddcTS2Hg30uUk-S-Rf78t4wtPXFX_pYBJOO_NH6lRQRYItX69iOEc27AlyoOKRUzeOs4HxxDt83tN5ineLIpNlbNMHG0C5oeKGsxyd6_IAGHgBb-SVWtXoqaOXyXdWYTiYOhM1SoYnR6oKbka23NOw",
  "payload": "ewogICJpZGVudGlmaWVycyI6IFsKICAgIHsKICAgICAgInR5cGUiOiAiZG5zIiwKICAgICAgInZhbHVlIjogImJhY2tlbmQuYXJpZmlucG9ydGZvbGlvLm15LmlkIgogICAgfQogIF0KfQ"
}
2023-09-02 01:22:07,314:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/new-order HTTP/1.1" 429 213
2023-09-02 01:22:07,315:DEBUG:acme.client:Received response:
HTTP 429
Server: nginx
Date: Sat, 02 Sep 2023 01:22:07 GMT
Content-Type: application/problem+json
Content-Length: 213
Connection: keep-alive
Boulder-Requester: 1287359976
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: De3Ke-Sk3_9iMwU0Kon5TNj_b3WhBZaR16k4HEM2fw9I4GJDt5M

{
  "type": "urn:ietf:params:acme:error:rateLimited",
  "detail": "Error creating new order :: too many failed authorizations recently: see https://letsencrypt.org/docs/failed-validation-limit/",
  "status": 429
}
2023-09-02 01:22:07,315:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 33, in <module>
    sys.exit(load_entry_point('certbot', 'console_scripts', 'certbot')())
  File "/opt/certbot/src/certbot/certbot/main.py", line 19, in main
    return internal_main.main(cli_args)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1864, in main
    return config.func(config, plugins)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1597, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 141, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 517, in obtain_and_enroll_certificate
    cert, chain, key, _ = self.obtain_certificate(domains)
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 428, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 478, in _get_order_and_authorizations
    orderr = self.acme.new_order(csr_pem)
  File "/opt/certbot/src/acme/acme/client.py", line 138, in new_order
    response = self._post(self.directory['newOrder'], order)
  File "/opt/certbot/src/acme/acme/client.py", line 366, in _post
    return self.net.post(*args, **kwargs)
  File "/opt/certbot/src/acme/acme/client.py", line 739, in post
    return self._post_once(*args, **kwargs)
  File "/opt/certbot/src/acme/acme/client.py", line 752, in _post_once
    response = self._check_response(response, content_type=content_type)
  File "/opt/certbot/src/acme/acme/client.py", line 603, in _check_response
    raise messages.Error.from_json(jobj)
acme.messages.Error: urn:ietf:params:acme:error:rateLimited :: There were too many requests of a given type :: Error creating new order :: too many failed authorizations recently: see https://letsencrypt.org/docs/failed-validation-limit/
2023-09-02 01:22:07,318:ERROR:certbot._internal.log:An unexpected error occurred:
2023-09-02 01:22:07,318:ERROR:certbot._internal.log:Error creating new order :: too many failed authorizations recently: see https://letsencrypt.org/docs/failed-validation-limit/
